// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bound_qp_cpp
Rcpp::List bound_qp_cpp(const arma::mat& D, const arma::vec& d, const arma::vec& lb);
RcppExport SEXP _spacexr_bound_qp_cpp(SEXP DSEXP, SEXP dSEXP, SEXP lbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lb(lbSEXP);
    rcpp_result_gen = Rcpp::wrap(bound_qp_cpp(D, d, lb));
    return rcpp_result_gen;
END_RCPP
}
// irwls_batch_cpp
Rcpp::List irwls_batch_cpp(const arma::mat& S_base, const arma::vec& nUMI, const arma::mat& beads, const arma::mat& Q_mat, const arma::mat& SQ_mat, const arma::vec& X_vals, const double K_val, const double min_change, const int n_iter, const int n_threads);
RcppExport SEXP _spacexr_irwls_batch_cpp(SEXP S_baseSEXP, SEXP nUMISEXP, SEXP beadsSEXP, SEXP Q_matSEXP, SEXP SQ_matSEXP, SEXP X_valsSEXP, SEXP K_valSEXP, SEXP min_changeSEXP, SEXP n_iterSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S_base(S_baseSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nUMI(nUMISEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beads(beadsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q_mat(Q_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SQ_mat(SQ_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X_vals(X_valsSEXP);
    Rcpp::traits::input_parameter< const double >::type K_val(K_valSEXP);
    Rcpp::traits::input_parameter< const double >::type min_change(min_changeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(irwls_batch_cpp(S_base, nUMI, beads, Q_mat, SQ_mat, X_vals, K_val, min_change, n_iter, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spacexr_bound_qp_cpp", (DL_FUNC) &_spacexr_bound_qp_cpp, 3},
    {"_spacexr_irwls_batch_cpp", (DL_FUNC) &_spacexr_irwls_batch_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_spacexr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
